---
title: "EEB313 - Regression 2 Simon"
output: html_notebook
---

```{r, eval=FALSE}
library(tidyverse)
library(tinytex)
library(ggpubr)
library(deSolve)
library(ggalt)
library(lme4)
library(lmerTest)
library(MuMIn)
library(sjmisc)
library(nlme)
library(terra) 
library(sf)
library(maps)
library(ape)
library(RColorBrewer)
library(lsmeans)
```

```{r}
mosquito<- read.csv("clean_mosquito_data.csv")
```

```{r}
clean_mosquito<- mosquito %>% 
  filter((!is.na(Agfed)) &
           (!is.na(Agunf)) &
           (!is.na(Aggrv)) &
           (!is.na(Affed)) &
           (!is.na(Affunf)) &
           (!is.na(Afgrv)))

sum(is.na(clean_mosquito))
```

```{r}
#rename the columns and then seperate 

clean_mosquito$Ag_fed<-clean_mosquito$Agfed
clean_mosquito$Ag_unf<-clean_mosquito$Agunf
clean_mosquito$Ag_grv<-clean_mosquito$Aggrv
clean_mosquito$Af_fed<-clean_mosquito$Affed
clean_mosquito$Af_unf<-clean_mosquito$Affunf
clean_mosquito$Af_grv<-clean_mosquito$Afgrv

head(clean_mosquito)

# mosquito_long - have to change the format into a long dataset
mosquito_long<-clean_mosquito %>% 
  gather("species","abundance", Ag_fed:Af_grv) #gather the species columns together

head(mosquito_long)

# remove the old columns
mosquito_long<-mosquito_long %>% 
  dplyr::select(-"Agfed", -"Agunf", -"Aggrv", -"Affed", -"Affunf", -"Afgrv")

# now seperate the species column into a "species" column and a "status" column - have to yse str_split_fixed
mosquito_long[c("species", "status")] <- str_split_fixed(mosquito_long$species, "_",2)
head(mosquito_long)

```


```{r}
#Multiple Regression 1, Hypothesis 2
mos_long_2.1<- mosquito_long %>% 
  filter(status == "fed") #only fed state mosquitoes

MR2.1<- lm(abundance ~ MeanTemp * MeanHum + species, #interested on temp and hum on fed state and species as direct effect
           data = mos_long_2.1)

summary(MR2.1)
```
```{r}
#Check assumptions for each linear model
plot(MR2.1, 1:2)
```

```{r}
#Multiple Regression 2, Hypothesis 2
mos_long_2.2<- mosquito_long %>% 
  filter(status == "unf") #only unfed state mosquitoes

MR2.2<- lm(abundance ~ MeanTemp * MeanHum + species, #interested on temp and hum on unfed state
           data = mos_long_2.2)

summary(MR2.2)
```
```{r}
plot(MR2.2, 1:2)
```


```{r}
#Multiple Regression 3, Hypothesis 2
mos_long_2.3<- mosquito_long %>% 
  filter(status == "grv") #only gravid state mosquitoes

MR2.3<- lm(abundance ~ MeanTemp * MeanHum + species, #interested on temp and hum on gravid state
           data = mos_long_2.3)

summary(MR2.3)
```

```{r}
plot(MR2.3, 1:2)
```

```{r}
#to compare, the following are the same as above, but are modified to see if the assumptions are better met
#can omit based on length of paper

MR2.1.trans<- lm(log10(abundance) ~ MeanTemp * MeanHum + species, #interested on temp and hum on fed state
           data = mos_long_2.1)

summary(MR2.1.trans)

MR2.2.trans<- lm(log10(abundance) ~ MeanTemp * MeanHum + species, #interested on temp and hum on unfed state
           data = mos_long_2.2)

summary(MR2.2.trans)

MR2.3.trans<- lm(log10(abundance) ~ MeanTemp * MeanHum + species, #interested on temp and hum on gravid state
           data = mos_long_2.3)

summary(MR2.3.trans)
```

```{r}
#assumption checks
plot(MR1.1.trans, 1:2)
plot(MR1.2.trans, 1:2)
plot(MR1.3.trans, 1:2)
```






```{r}
#plot abundance in function of species for fed state

abun_means_fed <- data.frame(summary(lsmeans(MR2.1, specs="species")))
abun_means_fed

ggplot(abun_means_fed, aes(x=species, y=lsmean, colour=species)) +
geom_errorbar(aes(ymin=lsmean-SE, ymax=lsmean+SE)) +
geom_point() +
theme_classic()
```


```{r}
#plot abundance in function of species for unfed state

abun_means_unf <- data.frame(summary(lsmeans(MR2.2, specs="species")))
abun_means_unf

ggplot(abun_means_unf, aes(x=species, y=lsmean, colour=species)) +
geom_errorbar(aes(ymin=lsmean-SE, ymax=lsmean+SE)) +
geom_point() +
theme_classic()
```


```{r}
#plot abundance in function of species for fed state

abun_means_grv <- data.frame(summary(lsmeans(MR2.3, specs="species")))
abun_means_grv

ggplot(abun_means_grv, aes(x=species, y=lsmean, colour=species)) +
geom_errorbar(aes(ymin=lsmean-SE, ymax=lsmean+SE)) +
geom_point() +
theme_classic()
```


